name: Re-ReND
dependencies:
- python
- pytorch=1.13.1
- torchvision=0.14.1
- pytorch-cuda=11.7
- cuda=11.7
- embree=2.17.7
- pyembree=0.1.6
- pip
- anaconda
#- gcc<10
#- cxx-compiler
- scikit-learn=0.24.2
- scikit-image=0.19.3
- scikit-fmm
- imageio
- numpy
- pillow
- PyYAML
- tqdm
- opencv-python-headless
- matplotlib
- imageio-ffmpeg
- pip:
  - pymeshlab
  - PyMCubes==0.1.2
  - trimesh==3.12.9
  - lpips==0.1.4
  - wandb
  - torchmetrics==0.10.1
#  - PyYAML>=6
#  - Pillow==9.0.1
#  - numpy==1.21.5
#  - opencv-python-headless==4.5.3.56
#  - tqdm==4.61.2
  - configargparse==1.5.1
#  - matplotlib==3.4.2
#  - imageio-ffmpeg==0.4.7
#  - imageio==2.9.0
  - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
channels:
  - nvidia/label/cuda-11.7.0
  - pytorch
  - anaconda
  - conda-forge
  - fastai
  - defaults
